In [27]:
#Check your development environment is working correctly
import sklearn
import numpy as np
import pandas as pd

print('The scikit-learn version is {}.'.format(sklearn.__version__))
if(sklearn.__version__ != "0.19.2"):
    print("This course was coded using sklearn 0.19.2.  Most things will work, but there are likely many that will not. You can proceed, but at your own risk.")

The scikit-learn version is 0.19.2.


In [28]:
data = pd.read_csv("data/L1Data.csv")
data

Class   Age  Funds Sale
0    Freshmen  18.0  600.0   No
1    Freshmen  18.0  500.0   No
2    Freshmen  18.0  600.0   No
3      Senior  23.0  800.0   No
4      Junior  21.0  400.0  Yes
5    Freshmen  19.0  600.0   No
6    Freshmen  20.0  600.0   No
7      Senior  24.0    NaN  Yes
8   Sophomore  23.0  620.0  Yes
9   Sophomore  25.0  800.0  Yes
10     Junior  21.0  900.0   No
11     Junior  21.0  650.0  Yes
12  Sophomore   NaN  500.0   No
13     Junior  21.0  800.0   No
14     Junior  20.0  650.0  Yes
15  Sophomore  21.0  580.0  Yes
16  Sophomore  20.0  800.0  Yes
17     Senior  26.0    NaN  Yes
18     Senior  25.0    NaN  Yes
19     Senior  41.0    NaN  Yes
20  Sophomore   NaN  500.0   No
21   Freshmen  18.0  500.0   No
22   Freshmen  18.0  500.0   No
23   Freshmen  18.0  600.0   No

In [31]:
X = data[["Class", "Age", "Funds"]].values
X

array([['Freshmen', 18.0, 600.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0],
       ['Senior', 23.0, 800.0],
       ['Junior', 21.0, 400.0],
       ['Freshmen', 19.0, 600.0],
       ['Freshmen', 20.0, 600.0],
       ['Senior', 24.0, nan],
       ['Sophomore', 23.0, 620.0],
       ['Sophomore', 25.0, 800.0],
       ['Junior', 21.0, 900.0],
       ['Junior', 21.0, 650.0],
       ['Sophomore', nan, 500.0],
       ['Junior', 21.0, 800.0],
       ['Junior', 20.0, 650.0],
       ['Sophomore', 21.0, 580.0],
       ['Sophomore', 20.0, 800.0],
       ['Senior', 26.0, nan],
       ['Senior', 25.0, nan],
       ['Senior', 41.0, nan],
       ['Sophomore', nan, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0]], dtype=object)

In [33]:
y = data[["Sale"]].values

In [34]:
X

array([['Freshmen', 18.0, 600.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0],
       ['Senior', 23.0, 800.0],
       ['Junior', 21.0, 400.0],
       ['Freshmen', 19.0, 600.0],
       ['Freshmen', 20.0, 600.0],
       ['Senior', 24.0, nan],
       ['Sophomore', 23.0, 620.0],
       ['Sophomore', 25.0, 800.0],
       ['Junior', 21.0, 900.0],
       ['Junior', 21.0, 650.0],
       ['Sophomore', nan, 500.0],
       ['Junior', 21.0, 800.0],
       ['Junior', 20.0, 650.0],
       ['Sophomore', 21.0, 580.0],
       ['Sophomore', 20.0, 800.0],
       ['Senior', 26.0, nan],
       ['Senior', 25.0, nan],
       ['Senior', 41.0, nan],
       ['Sophomore', nan, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0]], dtype=object)

In [37]:
from sklearn.preprocessing import Imputer
imputing_configuration = Imputer(missing_values = 'NaN', strategy="mean")
imputed_values = imputing_configuration.fit(X[:,[1,2]])
X[:,[1,2]] = imputed_values.transform(X[:,[1,2]])
X

array([['Freshmen', 18.0, 600.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0],
       ['Senior', 23.0, 800.0],
       ['Junior', 21.0, 400.0],
       ['Freshmen', 19.0, 600.0],
       ['Freshmen', 20.0, 600.0],
       ['Senior', 24.0, 625.0],
       ['Sophomore', 23.0, 620.0],
       ['Sophomore', 25.0, 800.0],
       ['Junior', 21.0, 900.0],
       ['Junior', 21.0, 650.0],
       ['Sophomore', 21.772727272727273, 500.0],
       ['Junior', 21.0, 800.0],
       ['Junior', 20.0, 650.0],
       ['Sophomore', 21.0, 580.0],
       ['Sophomore', 20.0, 800.0],
       ['Senior', 26.0, 625.0],
       ['Senior', 25.0, 625.0],
       ['Senior', 41.0, 625.0],
       ['Sophomore', 21.772727272727273, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 500.0],
       ['Freshmen', 18.0, 600.0]], dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder
discreteCoder_X = LabelEncoder()

X[:,0] = discreteCoder_X.fit_transform(X[:,0])
X

array([[0, 18.0, 600.0],
       [0, 18.0, 500.0],
       [0, 18.0, 600.0],
       [2, 23.0, 800.0],
       [1, 21.0, 400.0],
       [0, 19.0, 600.0],
       [0, 20.0, 600.0],
       [2, 24.0, 625.0],
       [3, 23.0, 620.0],
       [3, 25.0, 800.0],
       [1, 21.0, 900.0],
       [1, 21.0, 650.0],
       [3, 21.772727272727273, 500.0],
       [1, 21.0, 800.0],
       [1, 20.0, 650.0],
       [3, 21.0, 580.0],
       [3, 20.0, 800.0],
       [2, 26.0, 625.0],
       [2, 25.0, 625.0],
       [2, 41.0, 625.0],
       [3, 21.772727272727273, 500.0],
       [0, 18.0, 500.0],
       [0, 18.0, 500.0],
       [0, 18.0, 600.0]], dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder
discreteCoder_X_dummies = OneHotEncoder(categorical_features = [0])
X = discreteCoder_X_dummies.fit_transform(X).toarray()
X

array([[  1.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  18.        , 600.        ],
       [  1.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  18.        , 500.        ],
       [  1.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  18.        , 600.        ],
       [  0.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  23.        , 800.        ],
       [  0.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  21.        , 400.        ],
       [  1.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  19.        , 600.        ],
       [  1.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  20.        , 600.        ],
       [  0.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.       

In [17]:
discreteCoder_y = LabelEncoder()
y = discreteCoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0])

In [19]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1693)


In [22]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [24]:
from sklearn.preprocessing import StandardScaler
scale_X = StandardScaler()

#Note I add the "_std" here.
#This is better practice than what I have in the video,
#as you don't overwrite your original X_train.
#This can be a particular issue when you're using notebooks.
X_train_std = scale_X.fit_transform(X_train)
X_train_std

array([[-0.67936622,  0.67936622, -0.67936622,  1.93649167, -0.5976143 ,
        -0.51639778, -0.24692088,  0.14633175],
       [-0.67936622,  0.67936622, -0.67936622, -0.51639778,  1.67332005,
        -0.51639778,  0.7398184 , -0.06429728],
       [ 1.47196014, -1.47196014,  1.47196014, -0.51639778, -0.5976143 ,
        -0.51639778, -0.83896446, -1.11744247],
       [-0.67936622,  0.67936622, -0.67936622,  1.93649167, -0.5976143 ,
        -0.51639778, -0.24692088, -1.95995861],
       [ 1.47196014, -1.47196014,  1.47196014, -0.51639778, -0.5976143 ,
        -0.51639778, -0.44426874, -0.27492632],
       [-0.67936622,  0.67936622, -0.67936622, -0.51639778, -0.5976143 ,
         1.93649167,  0.14777483, -0.10642309],
       [-0.67936622,  0.67936622, -0.67936622, -0.51639778, -0.5976143 ,
         1.93649167,  0.54247055,  1.41010597],
       [-0.67936622,  0.67936622, -0.67936622, -0.51639778,  1.67332005,
        -0.51639778,  3.70003627, -0.06429728],
       [-0.67936622,  0.67936622

In [26]:
X_test_std = scale_X.transform(X_test)
X_test_std

array([[-0.67936622,  0.67936622, -0.67936622,  1.93649167, -0.5976143 ,
        -0.51639778, -0.24692088,  1.41010597],
       [-0.67936622,  0.67936622, -0.67936622, -0.51639778, -0.5976143 ,
         1.93649167, -0.24692088, -0.44342955],
       [ 1.47196014, -1.47196014,  1.47196014, -0.51639778, -0.5976143 ,
        -0.51639778, -0.83896446, -0.27492632],
       [ 1.47196014, -1.47196014,  1.47196014, -0.51639778, -0.5976143 ,
        -0.51639778, -0.83896446, -1.11744247],
       [-0.67936622,  0.67936622, -0.67936622, -0.51639778, -0.5976143 ,
         1.93649167, -0.09442481, -1.11744247]])